- hosts: all
  become: yes
  tasks:
    - name: Garantir que sngrep está instalado
      ansible.builtin.apt:
        name: sngrep
        state: present

    - name: Garantir que nmon está instalado
      ansible.builtin.apt:
        name: nmon
        state: present

    - name: Garantir que o htop está instalado
      ansible.builtin.apt:
        name: htop
        state: present

    - name: Garantir que o ncdu está instalado
      ansible.builtin.apt:
        name: ncdu
        state: present

    - name: Garantir que o tcpdumo está instalado
      ansible.builtin.apt:
        name: tcpdump
        state: present

    - name: Coletar serviços
      ansible.builtin.service_facts:

    - name: Ativar NTP se timesyncd não estiver ativo
      command: timedatectl set-ntp true
      when: "'systemd-timesyncd.service' not in ansible_facts.services or ansible_facts.services['systemd-timesyncd.service'].state != 'running'"

    - name: Garantir que timesyncd está ativo
      ansible.builtin.service:
        name: systemd-timesyncd
        state: started
        enabled: yes
