- hosts: all
  tasks:
    - name: Garantir que sngrep está instalado
      ansible.builtin.apt:
        name: sngrep
        state: present

    - name: Garantir que nmon está instalado
      ansible.builtin.apt:
        name: nmon
        state: present
